version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  script:
    build: ./run_script
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    command: flask run --host=0.0.0.0