debug: yes

host: 127.0.0.1
port: 3030

clean_files_on_start: false

commands:
  python:
    - python3
    - -m
    - pyls
    - -v
  cpp:
    - ccls
    - >
      --init={
        "index":{
          "onChange":true,
          "trackDependency":0,
          "threads":2,
          "comments":0,
          "initialBlacklist":["."],
        },
        "cache":{
          "retainInMemory":0,
        },
        "diagnostics":{
          "onSave":1500,
        }
      }
